### ISSUE TITLE
Contextsidebar not working in MPS 3.2

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1167]
When I enable the tool in the ContextSidebarManager by commenting in the related code in the init and dispose methods of the component, every time the tool window is opened a classloader exception is thrown. I have also tried to experiment with the solution kind but it does not change anything.

[2636992]  ERROR - llij.ide.plugins.PluginManager - ClassLoader of the module 'com.mbeddr.mpsutil.contextsidebar.runtime [solution]' is disposed and not operable!
jetbrains.mps.classloading.ModuleClassLoader$ModuleClassLoaderIsDisposedException: ClassLoader of the module 'com.mbeddr.mpsutil.contextsidebar.runtime [solution]' is disposed and not operable!
	at jetbrains.mps.classloading.ModuleClassLoader.checkNotDisposed(ModuleClassLoader.java:70)
	at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:102)
	at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.mbeddr.mpsutil.contextsidebar.runtime.VerticalLayout.layoutSize(VerticalLayout.java:93)
	at com.mbeddr.mpsutil.contextsidebar.runtime.VerticalLayout.preferredLayoutSize(VerticalLayout.java:163)
	at java.awt.Container.preferredSize(Container.java:1794)
	at java.awt.Container.getPreferredSize(Container.java:1778)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1508)
	at java.awt.Container.doLayout(Container.java:1497)
	at java.awt.Container.validateTree(Container.java:1693)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validate(Container.java:1628)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:704)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:702)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:701)
	at com.intellij.ide.IdeRepaintManager.validateInvalidComponents(IdeRepaintManager.java:106)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1719)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by enikao** [comment]
I'm confident this does not happen any more after the recent ContextSidebar refactoring.
