### ISSUE TITLE
NodeCastException after CMD+P on a FunctionCall

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1209]
```
jetbrains.mps.lang.smodel.generator.smodelAdapter.NodeCastException: Can't cast node: 7448993981563018718, concept: com.mbeddr.core.expressions.structure.UnsignedInt16tType to concept: com.mbeddr.core.modules.structure.IFunctionLike
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations.cast(SNodeOperations.java:726)
	at com.mbeddr.core.modules.editor.CallLikeParameterHint.getStyledMethodPresentation(CallLikeParameterHint.java:24)
	at com.mbeddr.core.modules.editor.CallLikeParameterHint.getStyledMethodPresentation(CallLikeParameterHint.java:1)
	at jetbrains.mps.ide.actions.ShowParameters_Action.createComponent(ShowParameters_Action.java:125)
	at jetbrains.mps.ide.actions.ShowParameters_Action.doExecute(ShowParameters_Action.java:101)
	at jetbrains.mps.workbench.action.BaseAction$4.run(BaseAction.java:144)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess$CommandRunnable$1.run(WorkbenchModelAccess.java:705)
	at jetbrains.mps.smodel.WriteActionDispatcher.run(WriteActionDispatcher.java:39)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess$3.run(WorkbenchModelAccess.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:164)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess$CommandRunnable.run(WorkbenchModelAccess.java:700)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.runWriteActionInCommand(WorkbenchModelAccess.java:539)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:502)
	at jetbrains.mps.project.ProjectModelAccess.executeCommand(ProjectModelAccess.java:36)
	at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:149)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:614)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:663)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:513)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:546)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by bkolb** [comment]
has been fixed in the meantime with another commit
