### ISSUE TITLE
Pattern Language: Runtime Solution not on Classpath

### ISSUE THREAD

**Issue by DomenikP** [mbeddr/mbeddr.core#1249]
I get the exception trace shown below in the command-line build, if I use the pattern language inside a generator. This problem does not appear when building in MPS.
It disappears after adding the runtime solution as dependency in my generator.

[generate] java.lang.NoClassDefFoundError: com/mbeddr/mpsutil/compare/pattern/generator/runtime/plugin/GeneratorUtils
[15:12:32][generate]    at com.lmsintl.accent.blocks.execution.generator.template.main.QueriesGenerated.baseMappingRule_Condition_9025951637831521583(QueriesGenerated.java:285)
[15:12:32][generate]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:12:32][generate]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:12:32][generate]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:12:32][generate]    at java.lang.reflect.Method.invoke(Method.java:497)
[15:12:32][generate]    at jetbrains.mps.util.QueryMethodGenerated$2.invoke(QueryMethodGenerated.java:206)
[15:12:32][generate]    at jetbrains.mps.generator.impl.interpreted.ReflectiveQueryProvider$Impl.check(ReflectiveQueryProvider.java:315)
[15:12:32][generate]    at jetbrains.mps.generator.impl.interpreted.TemplateReductionRuleInterpreted.isApplicable(TemplateReductionRuleInterpreted.java:56)
[15:12:32][generate]    at jetbrains.mps.generator.template.DefaultQueryExecutionContext.isApplicable(DefaultQueryExecutionContext.java:242)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateExecutionEnvironmentImpl.tryToReduce(TemplateExecutionEnvironmentImpl.java:343)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateExecutionEnvironmentImpl.trySwitch(TemplateExecutionEnvironmentImpl.java:169)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateProcessor$SwitchMacro.apply(TemplateProcessor.java:688)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateProcessor.applyMacro(TemplateProcessor.java:114)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateProcessor.applyTemplate(TemplateProcessor.java:136)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateProcessor$MacroImpl.nextMacro(TemplateProcessor.java:289)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateProcessor$LoopMacro.apply(TemplateProcessor.java:412)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateProcessor.applyMacro(TemplateProcessor.java:114)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateProcessor.applyTemplate(TemplateProcessor.java:136)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateProcessor.apply(TemplateProcessor.java:100)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateContainer.processRuleConsequence(TemplateContainer.java:79)
[15:12:32][generate]    at jetbrains.mps.generator.impl.interpreted.TemplateReductionRuleInterpreted.apply(TemplateReductionRuleInterpreted.java:65)
[15:12:32][generate]    at jetbrains.mps.generator.template.DefaultQueryExecutionContext.applyRule(DefaultQueryExecutionContext.java:230)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateExecutionEnvironmentImpl.tryToReduce(TemplateExecutionEnvironmentImpl.java:350)
[15:12:32][generate]    at jetbrains.mps.generator.impl.TemplateExecutionEnvironmentImpl.tryToReduce(TemplateExecutionEnvironmentImpl.java:305

**Comment by alexanderpann** [comment]
I'll close this issue as it is not relevant anymore. So much has changed in the meantime in regard to class loading, especially in 2024.1. Let's reopen the ticket when it happens again.
