### ISSUE TITLE
Unable to delete a big node

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1353]
When I try to delete a node, I get the following error:

java.lang.RuntimeException: Cannot set height to 17. Minimum height is 18
        at de.itemis.mps.editor.celllayout.runtime.LayoutableAdapter.setSize(LayoutableAdapter.java:60)
        at de.itemis.mps.editor.celllayout.runtime.AbstractLayoutableAdapter.setBounds(AbstractLayoutableAdapter.java:96)
        at de.itemis.mps.editor.celllayout.layout.Grid.applyLayout(Grid.java:313)
        at de.itemis.mps.editor.celllayout.layout.AbstractGridLayout.layout(AbstractGridLayout.java:42)
        at de.itemis.mps.editor.celllayout.runtime.LayoutableCollectionAdapter.relayout(LayoutableCollectionAdapter.java:116)
        at de.itemis.mps.editor.celllayout.layout.IndentLayout$Word.applyLayout(IndentLayout.java:580)
        at de.itemis.mps.editor.celllayout.layout.IndentLayout$Line.applyLayout(IndentLayout.java:486)
        at de.itemis.mps.editor.celllayout.layout.IndentLayout$Text.applyLayout(IndentLayout.java:348)
        at de.itemis.mps.editor.celllayout.layout.IndentLayout.layout(IndentLayout.java:43)
        at de.itemis.mps.editor.celllayout.runtime.LayoutableCollectionAdapter.relayout(LayoutableCollectionAdapter.java:116)
        at de.itemis.mps.editor.celllayout.layout.AbstractGridLayout.layout(AbstractGridLayout.java:48)
        at de.itemis.mps.editor.celllayout.runtime.LayoutableCollectionAdapter.relayout(LayoutableCollectionAdapter.java:116)
        at de.itemis.mps.editor.celllayout.layout.IndentLayout$Word.applyLayout(IndentLayout.java:580)
        at de.itemis.mps.editor.celllayout.layout.IndentLayout$Line.applyLayout(IndentLayout.java:486)
        at de.itemis.mps.editor.celllayout.layout.IndentLayout$Text.applyLayout(IndentLayout.java:348)
        at de.itemis.mps.editor.celllayout.layout.IndentLayout.layout(IndentLayout.java:43)
        at de.itemis.mps.editor.celllayout.runtime.LayoutableCollectionAdapter.relayout(LayoutableCollectionAdapter.java:116)
        at de.itemis.mps.editor.celllayout.runtime.LayoutEngine$2.run(LayoutEngine.java:61)
        at de.itemis.mps.editor.celllayout.runtime.LayoutWatchdog.enter(LayoutWatchdog.java:20)
        at de.itemis.mps.editor.celllayout.runtime.LayoutEngine.layoutSubtree(LayoutEngine.java:51)
        at de.itemis.mps.editor.celllayout.runtime.LayoutEngine.layoutSubtree(LayoutEngine.java:40)
        at de.itemis.mps.editor.celllayout.runtime.LayoutEngine.layoutRootCell(LayoutEngine.java:36)
        at de.itemis.mps.editor.celllayout.runtime.LayoutInterceptor.doLayout(LayoutInterceptor.java:44)
        at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.relayoutImpl(EditorCell_Collection.java:502)
        at jetbrains.mps.nodeEditor.cells.EditorCell_Basic.relayout(EditorCell_Basic.java:847)
        at jetbrains.mps.nodeEditor.EditorComponent.doRelayout(EditorComponent.java:1788)
        at jetbrains.mps.nodeEditor.EditorComponent.relayout(EditorComponent.java:1775)
        at jetbrains.mps.nodeEditor.EditorContext$6.run(EditorContext.java:298)
        at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:96)
        at jetbrains.mps.nodeEditor.EditorContext.setMemento(EditorContext.java:295)
        at jetbrains.mps.nodeEditor.EditorComponent.setRootCell(EditorComponent.java:1653)
        at jetbrains.mps.nodeEditor.updater.UpdaterImpl.doUpdate(UpdaterImpl.java:111)
        at jetbrains.mps.nodeEditor.updater.UpdaterImpl.update(UpdaterImpl.java:93)
        at jetbrains.mps.nodeEditor.updater.UpdaterModelListener.eventsHappened(UpdaterModelListener.java:44)
        at jetbrains.mps.smodel.ModelsEventsCollector$1.run(ModelsEventsCollector.java:82)
        at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:125)
        at jetbrains.mps.smodel.ModelsEventsCollector.flush(ModelsEventsCollector.java:77)
        at jetbrains.mps.nodeEditor.updater.UpdaterModelListenersController.flush(UpdaterModelListenersController.java:116)
        at jetbrains.mps.nodeEditor.updater.UpdaterImpl.flushModelEvents(UpdaterImpl.java:155)
        at jetbrains.mps.nodeEditor.EditorContext.flushEvents(EditorContext.java:222)
        at jetbrains.mps.editor.runtime.selection.SelectionUtil.selectLabelCellAnSetCaret(SelectionUtil.java:37)
        at jetbrains.mps.nodeEditor.selection.NodeRangeSelection.selectNode(NodeRangeSelection.java:358)
        at jetbrains.mps.nodeEditor.selection.NodeRangeSelection.access$200(NodeRangeSelection.java:50)
        at jetbrains.mps.nodeEditor.selection.NodeRangeSelection$1.doExecute(NodeRangeSelection.java:304)
        at jetbrains.mps.editor.runtime.commands.EditorCommand.run(EditorCommand.java:52)
        at jetbrains.mps.smodel.WorkbenchModelAccess$CommandRunnable$1.run(WorkbenchModelAccess.java:642)
        at jetbrains.mps.smodel.WriteActionDispatcher.run(WriteActionDispatcher.java:39)
        at jetbrains.mps.smodel.WorkbenchModelAccess$3.run(WorkbenchModelAccess.java:135)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
        at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:144)
        at jetbrains.mps.smodel.WorkbenchModelAccess$CommandRunnable.run(WorkbenchModelAccess.java:637)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
        at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteActionInCommand(WorkbenchModelAccess.java:450)
        at jetbrains.mps.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:413)
        at jetbrains.mps.project.ProjectModelAccess.executeCommand(ProjectModelAccess.java:43)
        at jetbrains.mps.nodeEditor.selection.NodeRangeSelection.performDeleteAction(NodeRangeSelection.java:287)
        at jetbrains.mps.nodeEditor.selection.NodeRangeSelection.executeAction(NodeRangeSelection.java:212)
        at jetbrains.mps.ide.editor.actions.Delete_Action.doExecute(Delete_Action.java:55)
        at jetbrains.mps.workbench.action.BaseAction$2.run(BaseAction.java:145)
        at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:155)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by slisson** [comment]
How can I reproduce this exception?
