### ISSUE TITLE
Statemachine diagramatic notation does not work on milestone 15.3

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1512]
below is a stack-trace:

[ 258642]   WARN - or.cells.EditorCellFactoryImpl - Failed to create cell for node: [contents] Statemachine "Counter"[4215647619818948996] in mbeddr.tutorial.ma
in.analyses using default editor [node r:0d2d1e96-2ec7-4797-ad03-f95f261d35d7(mbeddr.tutorial.main.analyses)/4215647619818948996]
java.lang.IllegalStateException: @NotNull method de/itemis/mps/editor/diagram/runtime/model/AbstractDiagramElementAccessor.getRootEditorCell must not return nul
l
        at de.itemis.mps.editor.diagram.runtime.model.AbstractDiagramElementAccessor.getRootEditorCell(AbstractDiagramElementAccessor.java:46)
        at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory$4.invoke(AccessorFactory.java:117)
        at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory$4.invoke(AccessorFactory.java:1)
        at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory.visitAccessorProviders(AccessorFactory.java:137)
        at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory.visitAccessorProviders(AccessorFactory.java:131)
        at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory.collectAccessors(AccessorFactory.java:114)
        at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory.collectAccessors(AccessorFactory.java:109)
        at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory.fromSNode(AccessorFactory.java:61)
        at com.mbeddr.ext.statemachines.editor.Statemachine_graphical_Editor$1$1$1$1.getElements(Statemachine_graphical_Editor.java:240)
        at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer.collectAccessors(ModelSynchronizer.java:215)
        at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer.fromSModel_(ModelSynchronizer.java:230)
        at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer$7$1.run(ModelSynchronizer.java:199)
        at de.itemis.mps.editor.diagram.runtime.model.ScalableEditorCell.withScalingDisabled(ScalableEditorCell.java:27)
        at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer$7.run(ModelSynchronizer.java:197)
        at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:97)
        at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
        at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer.fromSModel(ModelSynchronizer.java:195)
        at de.itemis.mps.editor.diagram.runtime.model.DiagramModel$2.run(DiagramModel.java:223)
        at de.itemis.mps.editor.diagram.runtime.model.ScalableEditorCell.withScalingDisabled(ScalableEditorCell.java:27)
        at de.itemis.mps.editor.diagram.runtime.model.DiagramModel.synchronizeRead(DiagramModel.java:221)
        at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell$4.run(RootDiagramECell.java:137)
        at de.itemis.mps.editor.diagram.runtime.ContextVariables$1.run(ContextVariables.java:40)
        at de.itemis.mps.editor.diagram.runtime.ContextVariables.enterNewContext(ContextVariables.java:30)
        at de.itemis.mps.editor.diagram.runtime.ContextVariables.withValue(ContextVariables.java:37)
        at de.itemis.mps.editor.diagram.runtime.jgraph.BaseDiagramECell.withContextGraph(BaseDiagramECell.java:123)
        at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.<init>(RootDiagramECell.java:135)
        at com.mbeddr.ext.statemachines.editor.Statemachine_graphical_Editor$1$1$1.run(Statemachine_graphical_Editor.java:431)
        at de.itemis.mps.editor.diagram.runtime.ContextVariables$1.run(ContextVariables.java:40)
        at de.itemis.mps.editor.diagram.runtime.ContextVariables.enterNewContext(ContextVariables.java:30)
        at de.itemis.mps.editor.diagram.runtime.ContextVariables.withValue(ContextVariables.java:37)
        at com.mbeddr.ext.statemachines.editor.Statemachine_graphical_Editor$1$1.invoke(Statemachine_graphical_Editor.java:225)
        at de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext.createDiagram_(DiagramCreationContext.java:51)
        at de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext$1.run(DiagramCreationContext.java:29)
        at de.itemis.mps.editor.collapsible.runtime.CollapsibleContext.withFactory(CollapsibleContext.java:21)
        at de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext.createDiagram(DiagramCreationContext.java:27)
        at com.mbeddr.ext.statemachines.editor.Statemachine_graphical_Editor$1.run(Statemachine_graphical_Editor.java:223)
        at de.itemis.mps.editor.diagram.runtime.EditorUtil.noCaching(EditorUtil.java:137)
        at com.mbeddr.ext.statemachines.editor.Statemachine_graphical_Editor.createDiagram_4cak41_i0(Statemachine_graphical_Editor.java:221)
        at com.mbeddr.ext.statemachines.editor.Statemachine_graphical_Editor.createCollection_4cak41_a(Statemachine_graphical_Editor.java:95)
        at com.mbeddr.ext.statemachines.editor.Statemachine_graphical_Editor.createEditorCell(Statemachine_graphical_Editor.java:77)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:132)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:106)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:86)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_connectionLayoutInInspector.createNextEditor_46qgkg_a0a_0(BaseConcept
_conditionalEditor_Editor_connectionLayoutInInspector.java:65)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_connectionLayoutInInspector.createAlternation_46qgkg_a0(BaseConcept_c
onditionalEditor_Editor_connectionLayoutInInspector.java:50)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_connectionLayoutInInspector.createPriorityInfoCell_46qgkg_a(BaseConce
pt_conditionalEditor_Editor_connectionLayoutInInspector.java:36)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_connectionLayoutInInspector.createEditorCell(BaseConcept_conditionalE
ditor_Editor_connectionLayoutInInspector.java:29)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:132)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:106)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:86)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_boxLayoutInInspector.createNextEditor_46qgkg_a0a_0(BaseConcept_condit
ionalEditor_Editor_boxLayoutInInspector.java:65)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_boxLayoutInInspector.createAlternation_46qgkg_a0(BaseConcept_conditio
nalEditor_Editor_boxLayoutInInspector.java:50)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_boxLayoutInInspector.createPriorityInfoCell_46qgkg_a(BaseConcept_cond
itionalEditor_Editor_boxLayoutInInspector.java:36)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_boxLayoutInInspector.createEditorCell(BaseConcept_conditionalEditor_E
ditor_boxLayoutInInspector.java:29)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:132)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:106)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:96)
        at jetbrains.mps.nodeEditor.EditorManager.createEditorCell_internal(EditorManager.java:405)
        at jetbrains.mps.nodeEditor.EditorManager.createEditorCell(EditorManager.java:296)
        at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl$1.compute(UpdateSessionImpl.java:198)
        at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl$1.compute(UpdateSessionImpl.java:195)
        at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.runWithExplicitEditorHints(UpdateSessionImpl.java:291)
        at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.updateChildNodeCell(UpdateSessionImpl.java:195)
        at jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler.createNodeCell(RefNodeListHandler.java:80)
        at com.mbeddr.core.modules.editor.ImplementationModule_Editor$contentsListHandler_luh5hj_d0a.createNodeCell(ImplementationModule_Editor.java:506)
        at jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler.createInnerCells(AbstractCellListHandler.java:123)
        at jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler.createCells(AbstractCellListHandler.java:103)
        at jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler.createCells(AbstractCellListHandler.java:86)
        at com.mbeddr.core.modules.editor.ImplementationModule_Editor.createRefNodeList_luh5hj_d0a(ImplementationModule_Editor.java:484)
        at com.mbeddr.core.modules.editor.ImplementationModule_Editor.createCollection_luh5hj_a0(ImplementationModule_Editor.java:128)
        at com.mbeddr.core.modules.editor.ImplementationModule_Editor.createBreadcrumbEditor_luh5hj_a(ImplementationModule_Editor.java:63)
        at com.mbeddr.core.modules.editor.ImplementationModule_Editor.createEditorCell(ImplementationModule_Editor.java:59)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:132)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:106)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:86)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_connectionLayoutInInspector.createNextEditor_46qgkg_a0a_0(BaseConcept
_conditionalEditor_Editor_connectionLayoutInInspector.java:65)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_connectionLayoutInInspector.createAlternation_46qgkg_a0(BaseConcept_c
onditionalEditor_Editor_connectionLayoutInInspector.java:50)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_connectionLayoutInInspector.createPriorityInfoCell_46qgkg_a(BaseConce
pt_conditionalEditor_Editor_connectionLayoutInInspector.java:36)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_connectionLayoutInInspector.createEditorCell(BaseConcept_conditionalE
ditor_Editor_connectionLayoutInInspector.java:29)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:132)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:106)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:86)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_boxLayoutInInspector.createNextEditor_46qgkg_a0a_0(BaseConcept_condit
ionalEditor_Editor_boxLayoutInInspector.java:65)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_boxLayoutInInspector.createAlternation_46qgkg_a0(BaseConcept_conditio
nalEditor_Editor_boxLayoutInInspector.java:50)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_boxLayoutInInspector.createPriorityInfoCell_46qgkg_a(BaseConcept_cond
itionalEditor_Editor_boxLayoutInInspector.java:36)
        at de.itemis.mps.editor.diagram.layout.editor.BaseConcept_conditionalEditor_Editor_boxLayoutInInspector.createEditorCell(BaseConcept_conditionalEditor_E
ditor_boxLayoutInInspector.java:29)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:132)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:106)
        at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:96)
        at jetbrains.mps.nodeEditor.EditorManager.createEditorCell_internal(EditorManager.java:405)
        at jetbrains.mps.nodeEditor.EditorManager.createEditorCell(EditorManager.java:296)
        at jetbrains.mps.nodeEditor.EditorManager.createRootCell(EditorManager.java:97)
        at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.performUpdate(UpdateSessionImpl.java:149)
        at jetbrains.mps.nodeEditor.updater.UpdaterImpl.lambda$updateRootCell$0(UpdaterImpl.java:132)
        at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.doExecute(TypeContextManager.java:276)
        at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.execute(TypeContextManager.java:246)
        at jetbrains.mps.typesystem.inference.TypeContextManager.runTypecheckingAction(TypeContextManager.java:136)
        at jetbrains.mps.nodeEditor.updater.UpdaterImpl.updateRootCell(UpdaterImpl.java:132)
        at jetbrains.mps.nodeEditor.updater.UpdaterImpl.doUpdate(UpdaterImpl.java:113)
        at jetbrains.mps.nodeEditor.updater.UpdaterImpl.update(UpdaterImpl.java:88)
        at jetbrains.mps.nodeEditor.EditorComponent.rebuildEditorContent(EditorComponent.java:1848)
        at jetbrains.mps.nodeEditor.NodeEditorComponent.rebuildEditorContent(NodeEditorComponent.java:139)
        at com.mbeddr.mpsutil.refactoring.rt.util.EditorHintToggleAction$2.run(EditorHintToggleAction.java:83)
        at jetbrains.mps.smodel.WorkbenchModelAccess$2.run(WorkbenchModelAccess.java:105)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:850)
        at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:100)
        at com.mbeddr.mpsutil.refactoring.rt.util.EditorHintToggleAction.setSelected(EditorHintToggleAction.java:80)
        at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:43)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
        at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$673(ActionMenuItem.java:304)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:905)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$670(ActionMenuItem.java:112)
        at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
        at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
        at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:695)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by slisson** [comment]
This is fixed on the master (a511e3e9993fa1200a84acd012428f12578062d9) and on refactor/mps34 (5c5d10fb4843667aba11dc046c0687ef31d36e47)
