### ISSUE TITLE
NPE in FavouritesHelper

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1600]
No message
java.lang.NullPointerException
            at com.mbeddr.mpsutil.favourites.plugin.plugin.FavouritesHelper$8.accept(FavouritesHelper.java:64)
            at com.mbeddr.mpsutil.favourites.plugin.plugin.FavouritesHelper$8.accept(FavouritesHelper.java:62)
            at jetbrains.mps.internal.collections.runtime.IWhereFilter.invoke(IWhereFilter.java:12)
            at jetbrains.mps.internal.collections.runtime.IWhereFilter.invoke(IWhereFilter.java:7)
            at jetbrains.mps.internal.collections.runtime.impl.FilteringSequence$FilteringIterator.moveToNext(FilteringSequence.java:63)
            at jetbrains.mps.internal.collections.runtime.impl.FilteringSequence$FilteringIterator.hasNext(FilteringSequence.java:34)
            at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:59)
            at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
            at jetbrains.mps.internal.collections.runtime.impl.SortingSequence.inputSortedWithSelector(SortingSequence.java:51)
            at jetbrains.mps.internal.collections.runtime.impl.SortingSequence.iterator(SortingSequence.java:40)
            at jetbrains.mps.internal.collections.runtime.impl.FilteringSequence$FilteringIterator.init(FilteringSequence.java:56)
            at jetbrains.mps.internal.collections.runtime.impl.FilteringSequence$FilteringIterator.hasNext(FilteringSequence.java:31)
            at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:59)
            at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
            at jetbrains.mps.internal.collections.runtime.IterableUtils.visitAll(IterableUtils.java:14)
            at jetbrains.mps.internal.collections.runtime.AbstractSequence.visitAll(AbstractSequence.java:80)
            at com.mbeddr.mpsutil.projectview.runtime.tree.CustomTreeNode$4.run(CustomTreeNode.java:145)
            at jetbrains.mps.smodel.WorkbenchModelAccess$2.run(WorkbenchModelAccess.java:105)
            at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
            at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:100)
            at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
            at com.mbeddr.mpsutil.projectview.runtime.tree.CustomTreeNode.queryChildElements(CustomTreeNode.java:138)
            at com.mbeddr.mpsutil.projectview.runtime.tree.CustomTreeNode$3.run(CustomTreeNode.java:118)
            at com.mbeddr.mpsutil.projectview.runtime.tree.DependencyRecorder.rebuild(DependencyRecorder.java:22)
            at com.mbeddr.mpsutil.projectview.runtime.tree.CustomTreeNodesUpdater.recordChildrenLoad(CustomTreeNodesUpdater.java:48)
            at com.mbeddr.mpsutil.projectview.runtime.tree.CustomTreeNode.queryAndLoadChildren(CustomTreeNode.java:115)
            at com.mbeddr.mpsutil.projectview.runtime.tree.CustomTreeNode$2.run(CustomTreeNode.java:106)
            at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

**Comment by coolya** [comment]
Can't reproduce
