### ISSUE TITLE
java.lang.IllegalArgumentException exception in ChangesManager command queue: Argument for @NotNull parameter 'role' of jetbrains/mps/smodel/SNode.addChild must not be null

### ISSUE THREAD

**Issue by norro** [mbeddr/mbeddr.core#1606]
Exception is thrown when selecting, moving, or changing the size of a diagram box. I am using MPS 3.4.3 (same issue with 3.4.1 though) and mbeddr platform build nightly-364-MPS-3.4.2.

```
java.lang.IllegalArgumentException exception in ChangesManager command queue: Argument for @NotNull parameter 'role' of jetbrains/mps/smodel/SNode.addChild must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'role' of jetbrains/mps/smodel/SNode.addChild must not be null
	at jetbrains.mps.smodel.SNode.addChild(SNode.java)
	at jetbrains.mps.smodel.persistence.def.v9.ModelReader9Handler$NodeElementHandler.handleChild_5480414999147804248(ModelReader9Handler.java:560)
	at jetbrains.mps.smodel.persistence.def.v9.ModelReader9Handler$NodeElementHandler.access$3200(ModelReader9Handler.java:458)
	at jetbrains.mps.smodel.persistence.def.v9.ModelReader9Handler$NodeElementHandler$4.apply(ModelReader9Handler.java:512)
	at jetbrains.mps.smodel.persistence.def.v9.ModelReader9Handler.endElement(ModelReader9Handler.java:93)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at jetbrains.mps.vcspersistence.VCSPersistenceSupport.parseAndHandleExceptions(VCSPersistenceSupport.java:352)
	at jetbrains.mps.vcspersistence.VCSPersistenceSupport.readModel(VCSPersistenceSupport.java:209)
	at jetbrains.mps.vcspersistence.VCSPersistenceSupport.access$300(VCSPersistenceSupport.java:76)
	at jetbrains.mps.vcspersistence.VCSPersistenceSupport$3.run(VCSPersistenceSupport.java:239)
	at jetbrains.mps.smodel.WorkbenchModelAccess$2.run(WorkbenchModelAccess.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:100)
	at jetbrains.mps.vcspersistence.VCSPersistenceSupport.readModel(VCSPersistenceSupport.java:233)
	at jetbrains.mps.vcspersistence.VCSPersistenceUtil.loadFromOldMPSPersistence(VCSPersistenceUtil.java:82)
	at jetbrains.mps.vcspersistence.VCSPersistenceUtil.loadModel(VCSPersistenceUtil.java:36)
	at jetbrains.mps.vcs.changesmanager.BaseVersionUtil.getBaseVersionModel(BaseVersionUtil.java:104)
	at jetbrains.mps.vcs.changesmanager.ChangesTracking.update(ChangesTracking.java:198)
	at jetbrains.mps.vcs.changesmanager.ChangesTracking.access$100(ChangesTracking.java:91)
	at jetbrains.mps.vcs.changesmanager.ChangesTracking$12.run(ChangesTracking.java:360)
	at jetbrains.mps.vcs.changesmanager.SimpleCommandQueue$MyExecutorThread.run(SimpleCommandQueue.java:77)
```

Also reported with MPS: [MPS-25175](https://youtrack.jetbrains.com/issue/MPS-25175).

**Comment by norro** [comment]
Seems to happen when model is changed in general,, not just the diagram. So probably no relation to diagram editor.
