### ISSUE TITLE
Exception caused by DragSelectionMouseListener or LabelSelectionHandler

### ISSUE THREAD

**Issue by sergej-koscejev** [mbeddr/mbeddr.core#1715]
I'm constantly getting these exceptions in MPS 2017.1.2:
```
Position 0 is not allowed for EditorCell_Label: ")"
java.lang.AssertionError: Position 0 is not allowed for EditorCell_Label: ")"
	at jetbrains.mps.nodeEditor.cells.EditorCell_Label.setCaretPosition(EditorCell_Label.java:178)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Label.setCaretPosition(EditorCell_Label.java:168)
	at de.itemis.mps.selection.runtime.mouse.LabelSelectionHandler.createSelection(LabelSelectionHandler.java:19)
	at de.itemis.mps.selection.runtime.mouse.DragSelectionMouseListener.createSelection(DragSelectionMouseListener.java:123)
	at de.itemis.mps.selection.runtime.mouse.DragSelectionMouseListener.updateSelection(DragSelectionMouseListener.java:115)
	at de.itemis.mps.selection.runtime.mouse.DragSelectionMouseListener.updateSelection(DragSelectionMouseListener.java:141)
	at de.itemis.mps.selection.runtime.mouse.DragSelectionMouseListener.mouseDragged(DragSelectionMouseListener.java:147)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:320)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
	at java.awt.Component.processMouseMotionEvent(Component.java:6589)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by alexanderpann** [comment]
This issue was fixed a long time ago.
