### ISSUE TITLE
NPE in com.mbeddr.doc.placeGeneratedFiles.cleanDocGen

### ISSUE THREAD

**Issue by hnehls** [mbeddr/mbeddr.core#1832]
In case of clean workspace (no compiled java classes available, folders like classes_gen etc. to be created by Build Project) I get NPE when I try to Rebuild Project.

Used mbeddr version: mbeddr_2017_2.1.0.19582.9618fb3

java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.mbeddr.doc.plugin.GenerationHelper.getDocGenFolder(GenerationHelper.java:19)
	at com.mbeddr.doc.plugin.placeGeneratedFiles_Facet$Target_cleanDocGen$1.execute(placeGeneratedFiles_Facet.java:91)
	at jetbrains.mps.internal.make.runtime.script.Script$3.invoke(Script.java:292)
	at jetbrains.mps.internal.make.runtime.script.Script$3.invoke(Script.java:235)
	at jetbrains.mps.ide.make.WorkbenchMakeService$Controller.runJobWithMonitor(WorkbenchMakeService.java:325)
	at jetbrains.mps.internal.make.runtime.script.Script.executeTargets(Script.java:235)
	at jetbrains.mps.internal.make.runtime.script.Script.execute(Script.java:213)
	at jetbrains.mps.make.service.CoreMakeTask$1.invoke(CoreMakeTask.java:100)
	at jetbrains.mps.make.service.CoreMakeTask$1.invoke(CoreMakeTask.java:74)
	at jetbrains.mps.make.dependencies.MakeSequence.iterate(MakeSequence.java:53)
	at jetbrains.mps.make.service.CoreMakeTask.doRun(CoreMakeTask.java:74)
	at jetbrains.mps.ide.make.MakeTask$WorkbenchMakeTask.doRun(MakeTask.java:146)
	at jetbrains.mps.make.service.CoreMakeTask.run(CoreMakeTask.java:53)
	at jetbrains.mps.ide.make.MakeTask$2.run(MakeTask.java:66)
	at java.lang.Thread.run(Thread.java:745)

**Comment by alexanderpann** [comment]
This exception doesn't happen anymore.
