### ISSUE TITLE
Java exception when create and initialize char array  >4057 sized

### ISSUE THREAD

**Issue by mahmoudbt** [mbeddr/mbeddr.core#1939]
Create and initialize char array  with size 4057 char (json format content) as below:

char[4057] awsUpdateJsonstring = "{\"version\":936...";

F5 to refresh mbeddr

The content assigned to the string is removed

char[4057] awsUpdateJsonstring = "";

and we got a java exception : 

        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
        at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
        at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3800)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
        at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
        at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)

**Comment by stephaneberle9** [comment]
After some investigation, it turns out that this is not really an mbeddr bug, nor an MPS bug but a Java bug(!):

https://bugs.java.com/view_bug.do?bug_id=6882582

I've located the piece of code in mbeddr that is subject to that bug (the `propertyValue.matches("(\\\\.|[^\"])*")` expression in `com.mbeddr.core.pointers.constraints.StringLiteral_Constraints`) and will try to find a workaround.
