### ISSUE TITLE
com.mbeddr.mpsutil.ecore.ui: Throws ERROR - NoSwingUnderWriteAction

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#2058]
When importing a .xcore file to MPS via the [ImportEcoreAction](http://127.0.0.1:63320/node?ref=r%3A7006d523-6713-4a08-9415-556af9bf043b%28com.mbeddr.mpsutil.ecore.ui.plugin%29%2F6188061127599284841) the following exceptions is thrown

```
[76860340]  ERROR - n.impl.NoSwingUnderWriteAction - AWT events are not allowed inside write action: java.awt.FocusEvent[FOCUS_LOST,temporary,opposite=javax.swing.JComboBox[,0,0,248x27,layout=com.intellij.ide.ui.laf.intellij.MacIntelliJComboBoxUI$2,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ide.ui.laf.intellij.MacIntelliJComboBoxBorder@6d51fb87,flags=16777536,maximumSize=java.awt.Dimension[width=250,height=27],minimumSize=,preferredSize=java.awt.Dimension[width=250,height=27],isEditable=false,lightWeightPopupEnabled=true,maximumRowCount=8,selectedItemReminder=/Users/],cause=ACTIVATION] on com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x1155,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=961,maximumSize=,minimumSize=,preferredSize=]
java.lang.Throwable: AWT events are not allowed inside write action: java.awt.FocusEvent[FOCUS_LOST,temporary,opposite=javax.swing.JComboBox[,0,0,248x27,layout=com.intellij.ide.ui.laf.intellij.MacIntelliJComboBoxUI$2,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ide.ui.laf.intellij.MacIntelliJComboBoxBorder@6d51fb87,flags=16777536,maximumSize=java.awt.Dimension[width=250,height=27],minimumSize=,preferredSize=java.awt.Dimension[width=250,height=27],isEditable=false,lightWeightPopupEnabled=true,maximumRowCount=8,selectedItemReminder=/Users/],cause=ACTIVATION] on com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x1155,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=961,maximumSize=,minimumSize=,preferredSize=]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.openapi.application.impl.NoSwingUnderWriteAction.lambda$watchForEvents$0(NoSwingUnderWriteAction.java:36)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
	at java.awt.SentEvent.dispatch(SentEvent.java:70)
	at java.awt.DefaultKeyboardFocusManager$DefaultKeyboardFocusManagerSentEvent.dispatch(DefaultKeyboardFocusManager.java:217)
	at java.awt.DefaultKeyboardFocusManager.sendMessage(DefaultKeyboardFocusManager.java:244)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:731)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4774)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at sun.lwawt.LWWindowPeer.lambda$changeFocusedWindow$8(LWWindowPeer.java:1337)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at javax.swing.JFileChooser.showDialog(JFileChooser.java:758)
	at javax.swing.JFileChooser.showOpenDialog(JFileChooser.java:656)
	at com.mbeddr.mpsutil.ecore.ui.plugin.EcoreFileImporterUI.importEcoreFile(EcoreFileImporterUI.java:16)
	at com.mbeddr.mpsutil.ecore.ui.plugin.importEcoreAction_Action.doExecute(importEcoreAction_Action.java:50)
```

**How to reproduce** 
*  use com.mbeddr.platform in version: 1.2.21426.6b68798
* import xcore/ecore via [ImportEcoreAction](http://127.0.0.1:63320/node?ref=r%3A7006d523-6713-4a08-9415-556af9bf043b%28com.mbeddr.mpsutil.ecore.ui.plugin%29%2F6188061127599284841)

**Comment by arimer** [comment]
Similar problem appears in the  [exportEcoreModelAction](http://127.0.0.1:63320/node?ref=r%3A7006d523-6713-4a08-9415-556af9bf043b%28com.mbeddr.mpsutil.ecore.ui.plugin%29%2F3040426542818214336)

Here the exception is: 
```
java.lang.Throwable: AWT events are not allowed inside write action: java.awt.FocusEvent[FOCUS_LOST,temporary,opposite=javax.swing.JComboBox[,0,0,248x27,layout=com.intellij.ide.ui.laf.intellij.MacIntelliJComboBoxUI$2,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ide.ui.laf.intellij.MacIntelliJComboBoxBorder@6d51fb87,flags=16777536,maximumSize=java.awt.Dimension[width=250,height=27],minimumSize=,preferredSize=java.awt.Dimension[width=250,height=27],isEditable=false,lightWeightPopupEnabled=true,maximumRowCount=8,selectedItemReminder=/Users/],cause=ACTIVATION] on com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x1155,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=961,maximumSize=,minimumSize=,preferredSize=]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.openapi.application.impl.NoSwingUnderWriteAction.lambda$watchForEvents$0(NoSwingUnderWriteAction.java:36)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
	at java.awt.SentEvent.dispatch(SentEvent.java:70)
	at java.awt.DefaultKeyboardFocusManager$DefaultKeyboardFocusManagerSentEvent.dispatch(DefaultKeyboardFocusManager.java:217)
	at java.awt.DefaultKeyboardFocusManager.sendMessage(DefaultKeyboardFocusManager.java:244)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:731)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4774)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at sun.lwawt.LWWindowPeer.lambda$changeFocusedWindow$8(LWWindowPeer.java:1337)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at javax.swing.JFileChooser.showDialog(JFileChooser.java:758)
	at javax.swing.JFileChooser.showOpenDialog(JFileChooser.java:656)
	at com.mbeddr.mpsutil.ecore.ui.plugin.EcoreModelExporterUI.exportEcoreModel(EcoreModelExporterUI.java:18)
	at com.mbeddr.mpsutil.ecore.ui.plugin.exportEcoreModelAction_Action.doExecute(exportEcoreModelAction_Action.java:41)
```
