### ISSUE TITLE
Exception when using context menu on transient models

### ISSUE THREAD

**Issue by KemalSoysal** [mbeddr/mbeddr.core#2104]
2019-10-08 20:05:11,089 [ 438087]  ERROR - jetbrains.mps.workbench.action.BaseAction$1 - User's action doUpdate method failed. Action: Set Path to the Generated Artifacts to Be Reviewed. Class: com.mbeddr.mpsutil.codereview.pluginSolution.plugin.SetPathToGeneratedArtifactsToReviewAction_Action 
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.mbeddr.mpsutil.codereview.pluginSolution.plugin.SetPathToGeneratedArtifactsToReviewAction_Action.getOutputPath(SetPathToGeneratedArtifactsToReviewAction_Action.java:64)
	at com.mbeddr.mpsutil.codereview.pluginSolution.plugin.SetPathToGeneratedArtifactsToReviewAction_Action.isApplicable(SetPathToGeneratedArtifactsToReviewAction_Action.java:32)
	at com.mbeddr.mpsutil.codereview.pluginSolution.plugin.SetPathToGeneratedArtifactsToReviewAction_Action.doUpdate(SetPathToGeneratedArtifactsToReviewAction_Action.java:36)
	at jetbrains.mps.workbench.action.BaseAction$1.run(BaseAction.java:130)
	at jetbrains.mps.smodel.WorkbenchModelAccess.lambda$runReadAction$0(WorkbenchModelAccess.java:77)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:925)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:74)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
	at jetbrains.mps.workbench.action.BaseAction.update(BaseAction.java:121)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:256)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:333)
	at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:307)
	at com.intellij.openapi.actionSystem.impl.Utils.hasVisibleChildren(Utils.java:273)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:213)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:350)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu$MyPopupMenuListener.popupMenuWillBecomeVisible(ActionPopupMenuImpl.java:156)
	at javax.swing.JPopupMenu.firePopupMenuWillBecomeVisible(JPopupMenu.java:682)
	at javax.swing.JPopupMenu.setVisible(JPopupMenu.java:789)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.setVisible(ActionPopupMenuImpl.java:130)
	at javax.swing.JPopupMenu.show(JPopupMenu.java:965)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:125)
	at jetbrains.mps.ide.ui.tree.MPSTree.showPopup(MPSTree.java:429)
	at jetbrains.mps.ide.ui.tree.MPSTree.myMouseReleased(MPSTree.java:257)
	at jetbrains.mps.ide.ui.tree.MPSTree$MyMouseAdapter.mouseReleased(MPSTree.java:962)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:424)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by alexanderpann** [comment]
This issue should be fixed nowadays.
