### ISSUE TITLE
IndexOutOfBoundsException on MPS startup

### ISSUE THREAD

**Issue by uiterlix** [mbeddr/mbeddr.core#2143]
When starting MPS with the mbeddr platform plugins installed the application throws an IndexOutOfBoundsException. 

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1310)
	at com.mbeddr.mpsutil.contextactions.runtime.DescriptorCollector.start(DescriptorCollector.java:44)
```

It seems that the DescriptorCollector always assumes there's at least 1 open project on startup. That's not always the case.

**Comment by alexanderpann** [comment]
Closing because it seems to be fixed in [92a08ee](https://github.com/uiterlix/mbeddr.core/commit/92a08ee56f8d34dd3b1fb5d6b852952c65316613).
