### ISSUE TITLE
java.lang.ClassNotFoundException: SPreferencesPage

### ISSUE THREAD

**Issue by alexanderpann** [mbeddr/mbeddr.core#2289]
```
java.lang.ClassNotFoundException: com/mbeddr/mpsutil/spreferences/runtime/SPreferencesPage
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.intellij.openapi.options.ConfigurableEP.findClassOrNull(ConfigurableEP.java:326)
```

This problem is known and described in the [register](http://127.0.0.1:63320/node?ref=e78f91af-08a8-4a7a-bed6-b22739ed069a%2Fr%3Af9e42dff-7cc2-48de-b7f5-594a5da757ae%28com.mbeddr.mpsutil.spreferences.runtime%2Fcom.mbeddr.mpsutil.spreferences.runtime%29%2F5053883086740929243) method of the page. I guess the workaround is not working anymore.

**Comment by alexanderpann** [comment]
I haven't seen this issue in newer MPS versions anymore.
