### ISSUE TITLE
The user guide does not rebuild

### ISSUE THREAD

**Issue by mar9000** [mbeddr/mbeddr.core#2304]
In the `stable` branch the user guide present into the `tutorial` project does not rebuild, MPS version 2022.2. It seems related to the PlantUML version in use. After a full build (`build_mbeddr`) the project opens but need a new project library taht point to `artifacts/de.itemis.mps.extensions`. Then every error disappear but the *rebuild* fires this exception:
```
(java.lang.IllegalAccessError): class net.sourceforge.plantuml.png.PngIOMetadata (in unnamed module @0x369ee3d2) cannot access class com.sun.imageio.plugins.png.PNGMetadata (in module java.desktop) because module java.desktop does not export com.sun.imageio.plugins.png to unnamed module @0x369ee3d2
java.lang.IllegalAccessError: class net.sourceforge.plantuml.png.PngIOMetadata (in unnamed module @0x369ee3d2) cannot access class com.sun.imageio.plugins.png.PNGMetadata (in module java.desktop) because module java.desktop does not export com.sun.imageio.plugins.png to unnamed module @0x369ee3d2
	at net.sourceforge.plantuml.png.PngIOMetadata.writeWithMetadata(PngIOMetadata.java:52)
	at net.sourceforge.plantuml.png.PngIO.write(PngIO.java:80)
	at net.sourceforge.plantuml.png.PngIO.write(PngIO.java:74)
	at net.sourceforge.plantuml.ugraphic.g2d.UGraphicG2d.writeImageTOBEMOVED(UGraphicG2d.java:208)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:146)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:123)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:124)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:77)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:312)
	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:201)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagram(UmlDiagram.java:225)
	at net.sourceforge.plantuml.SourceStringReader.generateImage(SourceStringReader.java:109)
	at net.sourceforge.plantuml.SourceStringReader.generateImage(SourceStringReader.java:96)
	at net.sourceforge.plantuml.SourceStringReader.generateImage(SourceStringReader.java:86)
	at com.mbeddr.doc.generator.template.main.QueriesGenerated.mappingScript_CodeBlock_2(QueriesGenerated.java:198)
	at com.mbeddr.doc.generator.template.main.QueriesGenerated$SCB.invoke(QueriesGenerated.java:543)
	at jetbrains.mps.generator.impl.interpreted.TemplateMappingScriptInterpreted.apply(TemplateMappingScriptInterpreted.java:74)
	at jetbrains.mps.generator.template.DefaultQueryExecutionContext.executeScript(DefaultQueryExecutionContext.java:299)
	at jetbrains.mps.generator.impl.TemplateGenerator.executeScript(TemplateGenerator.java:302)
	at jetbrains.mps.generator.impl.GenerationSession.preProcessModel(GenerationSession.java:623)
	at jetbrains.mps.generator.impl.GenerationSession.executeMajorStepInternal(GenerationSession.java:458)
	at jetbrains.mps.generator.impl.GenerationSession.executeMajorStep(GenerationSession.java:437)
	at jetbrains.mps.generator.impl.GenerationSession.processGenPlanBranch(GenerationSession.java:293)
	at jetbrains.mps.generator.impl.GenerationSession.generateModel(GenerationSession.java:208)
	at jetbrains.mps.generator.impl.GenerationController.generateModel(GenerationController.java:145)
	at jetbrains.mps.generator.impl.GenerationController.generate(GenerationController.java:73)
	at jetbrains.mps.generator.GenerationFacade.process0(GenerationFacade.java:178)
	at jetbrains.mps.generator.GenerationFacade.process(GenerationFacade.java:161)
	at jetbrains.mps.lang.core.plugin.Generate_Facet$Target_generate$1.lambda$execute$1(Generate_Facet.java:457)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:98)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:135)
	at jetbrains.mps.smodel.LockRunnable.run(LockRunnable.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:915)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:84)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
	at jetbrains.mps.lang.core.plugin.Generate_Facet$Target_generate$1.execute(Generate_Facet.java:454)
	at jetbrains.mps.internal.make.runtime.script.Script.lambda$executeTargets$0(Script.java:308)
	at jetbrains.mps.ide.make.WorkbenchMakeService$Controller.runJobWithMonitor(WorkbenchMakeService.java:336)
	at jetbrains.mps.internal.make.runtime.script.Script.executeTargets(Script.java:253)
	at jetbrains.mps.internal.make.runtime.script.Script.execute(Script.java:231)
	at jetbrains.mps.make.service.CoreMakeTask.lambda$doRun$0(CoreMakeTask.java:101)
	at jetbrains.mps.make.dependencies.MakeSequence.iterate(MakeSequence.java:54)
	at jetbrains.mps.make.service.CoreMakeTask.doRun(CoreMakeTask.java:75)
	at jetbrains.mps.ide.make.MakeTask$WorkbenchMakeTask.doRun(MakeTask.java:148)
	at jetbrains.mps.make.service.CoreMakeTask.run(CoreMakeTask.java:54)
	at jetbrains.mps.ide.make.MakeTask$2.run(MakeTask.java:68)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by alexanderpann** [comment]
Fixed on master (2022.3) in 808116a. We can backport the fix if needed to 2022.2.
