### ISSUE TITLE
IllegalArgumentException in com.mbeddr.mpsutil.contextactions.runtime

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#2403]
We are using the mbeddr.platform in version 2022.2.24492.bc2ece9 and are seeing the following exception on MPS startup:

```
Action dispatch failed. Thread ApplicationImpl pooled thread 7, state ACTIVE, 4 active clients.
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'withSession' of jetbrains/mps/typechecking/backend/TypecheckingSessionHandler.computeWithSession must not be null
    at jetbrains.mps.typechecking.backend.TypecheckingSessionHandler.$$$reportNull$$$0(TypecheckingSessionHandler.java)
    at jetbrains.mps.typechecking.backend.TypecheckingSessionHandler.computeWithSession(TypecheckingSessionHandler.java)
    at jetbrains.mps.intentions.IntentionsManager$IntentionsCollector.collect(IntentionsManager.java:213)
    at jetbrains.mps.intentions.IntentionsManager.getAvailableIntentions(IntentionsManager.java:221)
    at com.mbeddr.mpsutil.contextactions.runtime.IntentionActionSource.getActions(IntentionActionSource.java:53)
    at com.mbeddr.mpsutil.contextactions.runtime.WrapperActionSource$2.translate(WrapperActionSource.java:27)
    at com.mbeddr.mpsutil.contextactions.runtime.WrapperActionSource$2.translate(WrapperActionSource.java:25)
    at jetbrains.mps.internal.collections.runtime.ITranslator2.invoke(ITranslator2.java:12)
    at jetbrains.mps.internal.collections.runtime.ITranslator2.invoke(ITranslator2.java:7)
    at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.moveToNext(TranslatingSequence.java:82)
    at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.hasNext(TranslatingSequence.java:37)
    at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:59)
    at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
    at com.mbeddr.mpsutil.contextactions.runtime.ToolComponent.queryItems(ToolComponent.java:256)
    at com.mbeddr.mpsutil.contextactions.runtime.ToolComponent.lambda$update$1(ToolComponent.java:218)
    at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:98)
    at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:135)
    at jetbrains.mps.smodel.LockRunnable.run(LockRunnable.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:915)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:84)
    at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
    at com.mbeddr.mpsutil.contextactions.runtime.ToolComponent.lambda$update$4(ToolComponent.java:218)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by alexanderpann** [comment]
The code is executed in this pooled thread: [http://127.0.0.1:63320/node?ref=r%3Ae9a49de8-6adf-4c2e-b5c2-32fc88189c93%28com.mbeddr.mpsutil.contextactions.runtime%29%2F780885292938559332](http://127.0.0.1:63320/node?ref=r%3Ae9a49de8-6adf-4c2e-b5c2-32fc88189c93%28com.mbeddr.mpsutil.contextactions.runtime%29%2F780885292938559332)  
  
I never saw this exception. Maybe the type-checking plugin is not initialized yet?
